version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build: requirements/wp-fpm
    image: wordpress-image
    env_file:
      - .env
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb-image
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx-image
    ports:
      - "8080:443"
    volumes: 
      - ./web:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file: .env 

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/jbarbay/data/mariadb
      o : bind
      type : none
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/jbarbay/data/wordpress
      o : bind
      type : none

# volumes:
#   wordpress_data:
#   mariadb_data:


# version: "3.8"
# services:

#   mariadb:
#     container_name: mariadb
#     build: requirements/mariadb
#     image: mariadb-image
#     env_file: .env
#     volumes:
#       - mariadb:/var/lib/mysql
#     networks:
#       - inception
#     restart: always

#   wordpress:
#     container_name: wp-php
#     build: requirements/wp-fpm
#     image: wordpress-image
#     volumes: 
#       - ./web:/var/www/wordpress
#     depends_on:
#       - mariadb
#     env_file: .env
#     networks:
#       - inception
#     restart: always

#   nginx:
#     container_name: nginx
#     build: requirements/nginx
#     image: nginx-image
#     ports:
#       - "443:443"
#     volumes: 
#       - ./web:/var/www/wordpress
#     networks:
#       - inception
#     depends_on:
#       - wordpress
#     restart: unless-stopped
#     env_file: .env 


# volumes:
#   mariadb:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: /home/jbarbay/data/mariadb
#       o : bind
#       type : none
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       device: /home/jbarbay/data/wordpress
#       o : bind
#       type : none

# networks:
#   inception:
#     name: inception