version: "3.8"
services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb-image
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wp-php
    build: requirements/wordpress
    image: wordpress-image
    volumes: 
      - ./web:/var/www/html
    depends_on:
      - mariadb
    env_file: .env
    environment:
        WORDPRESS_DB_HOST: mariadb:3306
        WORDPRESS_DB_USER: ${MYSQL_USER}
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        WORDPRESS_DB_NAME: wordpress
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx-image
    ports:
      - "8080:443"
    volumes: 
      - ./web:/var/www/html
      # - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file: .env 

networks:
  inception:
    driver: bridge

volumes:
    mariadb_data: